### ISSUE TITLE
Error Loading Data

### ISSUE THREAD

**Issue by mf311** [argunsah/SpineS#6]
When I open the SpineS gui, and go to file -> load data -> and pick my images, I receive this error when I try to load them:

>> SpineS
Unable to resolve the name 'matlab.internal.cef.webwindowmanager.instance.windowList'.

Error in matlab.internal.webwindowmanager/get.windowList (line 114)
            implList = matlab.internal.cef.webwindowmanager.instance.windowList;

Error in matlab.internal.webwindowmanager/findAllWebwindows (line 88)
            list = obj.windowList;

Error in matlab.ui.internal.dialog.DialogUtils.disableAllWindowsSafely (line 40)
                webWindows = matlab.internal.webwindowmanager.instance.findAllWebwindows();

Error in inputdlg (line 378)
        c = matlab.ui.internal.dialog.DialogUtils.disableAllWindowsSafely(true);

Error in SpineS>importStack_Callback (line 433)
folderName  = cell2mat(inputdlg(prompt,name,numlines,defaultSize));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SpineS (line 77)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SpineS('importStack_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.

**Comment by argunsah** [comment]
Hello,
This error is about your matlab and has nothing to do with SpineS.
Please check the following page:

https://ch.mathworks.com/matlabcentral/answers/286677-problem-using-gui-in-figures-to-open-or-save

and maybe this:

https://ch.mathworks.com/matlabcentral/answers/397138-why-do-i-get-a-matlabwindow-application-failed-to-launch-error-when-launching-live-editor-app-des

Basically try running these commands:

restoredefaultpath

and after

savepath

and follow SpineS install and running instructions. 

Best,

Ali
